apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: manufacturer-vaultkubenertes-job
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: manufacturer-vaultkubenertes-job
  chart:
    git: https://github.com/PatStLouis/bevel.git
    ref: bevel-demo
    path: platforms/hyperledger-fabric/charts/vault_kubernetes
  values:
    metadata:
      name: manufacturer
      component_type: peer
      namespace: manufacturer-net    
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    vault:
      reviewer_service: vault-reviewer
      role: vault-role
      address: https://vault.interop.idlab.app
      authpath: localmanufacturer-net-auth
      policy: vault-crypto-peer-manufacturer-net-ro
      secret_path: secretsv2
      serviceaccountname: vault-auth
      imagesecretname: regcred
    
    k8s:
      kubernetes_url: https://10.0.20.51:6443
